server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service             # lb stands for load balancer
          predicates:
            - Path=/product-details/**          # if any request comes with this Path then redirect req to uri
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productFallBack   # if there is any failure forward it to FallBack
        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/price/**
          filters:
            - name: CircuitBreaker
              args:
                name: pricing-service
                fallbackuri: forward:/pricingFallBack
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventory-service
                fallbackuri: forward:/inventoryFallBack

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  commnd:
    fallbackcmd:
      execution:
        ioslation:
          thread:
            timeoutInMilliseconds: 5000     # If request is not returning anything after 5sec then only redirect request to FallBack

# server.port=8085
#spring.application.name=gateway-service
#
#spring.cloud.gateway.routes[0].id=product-service
#spring.cloud.gateway.routes[0].uri=lb://product-service
#spring.cloud.gateway.routes[0].predicates[0].name=Path
#spring.cloud.gateway.routes[0].predicates[0].args[patterns]=/product-details/**
#
#spring.cloud.gateway.routes[1].id=pricing-service
#spring.cloud.gateway.routes[1].uri=lb://pricing-service
#spring.cloud.gateway.routes[1].predicates[0].name=Path
#spring.cloud.gateway.routes[1].predicates[0].args[patterns]=/price/**
#
#spring.cloud.gateway.routes[2].id=inventory-service
#spring.cloud.gateway.routes[2].uri=lb://inventory-service
#spring.cloud.gateway.routes[2].predicates[0].name=Path
#spring.cloud.gateway.routes[2].predicates[0].args[patterns]=/inventory/**